<?php
require_once('tcpdf/tcpdf.php');
include("db_connection.php");

// Fetch all orders
$sql = "SELECT * FROM ordersss";
$result = $conn->query($sql);

// Create new PDF document
$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('SKL Admin');
$pdf->SetTitle('Work Details Report');
$pdf->SetHeaderData('', 0, 'Work Details Report', 'Generated by SKL Admin');
$pdf->setHeaderFont(Array('helvetica', '', 10));
$pdf->setFooterFont(Array('helvetica', '', 8));
$pdf->SetMargins(8, 20, 8);
$pdf->SetAutoPageBreak(TRUE, 15);
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 9);

// Table HTML
$html = '<h2 style="text-align:center;">Work Details - All Orders</h2>';
$html .= '<table border="1" cellpadding="3">
<tr style="background-color:#007bff; color:white; text-align:center;">
    <th>Order No</th>
    <th>PO Date</th>
    <th>Ship Date</th>
    <th>CK Date</th>
    <th>Fabric</th>
    <th>Trims</th>
    <th>Testing</th>
    <th>Cutting</th>
    <th>Printing</th>
    <th>Sewing</th>
    <th>Finishing</th>
    <th>Ship Sample</th>
    <th>Cycle</th>
</tr>';

while ($row = $result->fetch_assoc()) {
    $html .= '<tr>';
    $html .= '<td>' . $row['order_no'] . '</td>';
    $html .= renderCell($row['po_date'], $row['po_done_date'], $row['po_expected_date']);
    $html .= renderCell($row['ship_date'], $row['ship_done_date'], $row['ship_expected_date']);
    $html .= renderCell($row['ck_date'], $row['ck_done_date'], $row['ck_expected_date']);
    $html .= renderCell($row['fabric_date'], $row['fabric_done_date'], $row['fabric_expected_date']);
    $html .= renderCell($row['trims_date'], $row['trims_done_date'], $row['trims_expected_date']);
    $html .= renderCell($row['testing'], $row['testing_done_date'], $row['testing_expected_date']);
    $html .= renderCell($row['cutting'], $row['cutting_done_date'], $row['cutting_expected_date']);
    $html .= renderCell($row['printing'], $row['printing_done_date'], $row['printing_expected_date']);
    $html .= renderCell($row['sewing'], $row['sewing_done_date'], $row['sewing_expected_date']);
    $html .= renderCell($row['finishing'], $row['finishing_done_date'], $row['finishing_expected_date']);
    $html .= renderCell($row['ship_sample'], $row['ship_sample_done_date'], $row['ship_sample_expected_date']);
    $html .= checkCycleStatus($row);
    $html .= '</tr>';
}

$html .= '</table>';
$pdf->writeHTML($html);
$pdf->Output('work_details.pdf', 'I');

// Functions used
function renderCell($scheduled, $done, $expected) {
    $today = date('Y-m-d');
    $cell = "<b>$scheduled</b><br>";
    if (!empty($done)) {
        return '<td style="color:green;">' . $cell . 'Done: ' . $done . '</td>';
    } elseif (!empty($expected)) {
        return '<td style="color:red;">' . $cell . 'Expected: ' . $expected . '</td>';
    } elseif (!empty($scheduled) && $scheduled < $today) {
        return '<td style="color:red;">' . $cell . 'Not Done</td>';
    } else {
        return '<td>' . $cell . 'Not Done</td>';
    }
}

function checkCycleStatus($row) {
    $fields = ['po_done_date','ship_done_date','ck_done_date','fabric_done_date', 
               'trims_done_date','testing_done_date','cutting_done_date','printing_done_date', 
               'sewing_done_date','finishing_done_date','ship_sample_done_date'];
    foreach ($fields as $f) {
        if (empty($row[$f])) {
            return '<td style="color:orange;">In Progress</td>';
        }
    }
    return '<td style="color:green;">Completed</td>';
}
?>
